SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    ROUND(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100.0), 0) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
ON 
    C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV')
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE 
            C.CAR_ID = H.CAR_ID
            AND (
                (H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01') -- 대여 기간이 11월을 포함
                OR (H.START_DATE <= '2022-11-30' AND H.END_DATE > '2022-11-30') -- 대여 기간이 11월 전후를 포함
            )
    )
    AND C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100) BETWEEN 500000 AND 1999999
GROUP BY C.CAR_ID, C.CAR_TYPE, FEE
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;