-- 코드를 입력하세요
SELECT 
    R.CAR_ID, 
    R.CAR_TYPE, 
    FLOOR(R.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR R
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON R.CAR_TYPE = D.CAR_TYPE 
AND D.DURATION_TYPE = '30일 이상'
WHERE R.CAR_TYPE IN ('세단', 'SUV')
    AND R.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01'
    )
    AND FLOOR(R.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, R.CAR_TYPE, R.CAR_ID DESC;
