-- 코드를 입력하세요
SELECT 
U.USER_ID, 
U.NICKNAME, 
CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) 전체주소, 
CONCAT (SUBSTRING(TLNO, 1, 3), '-',
       SUBSTRING(TLNO, 4, 4), '-',
       SUBSTRING(TLNO, 8, 4)) 전화번호
FROM USED_GOODS_USER U
JOIN USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID
GROUP BY B.WRITER_ID HAVING COUNT(BOARD_ID) >= 3
ORDER BY U.USER_ID DESC;