-- 코드를 입력하세요
-- 중성화 Spayed, Neutered, 중성화 x Intact
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE '%Intact%' AND NOT O.SEX_UPON_OUTCOME LIKE '%Intact%'
ORDER BY I.ANIMAL_ID