-- 코드를 입력하세요
WITH RECURSIVE TIME AS 
    (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME WHERE HOUR < 23
    )

SELECT 
    T.HOUR AS HOUR,
    COUNT(ANIMAL_ID) AS COUNT
FROM TIME T
LEFT JOIN ANIMAL_OUTS O ON HOUR(O.DATETIME) = T.HOUR
GROUP BY T.HOUR
ORDER BY T.HOUR