-- 코드를 입력하세요
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
JOIN
    (
        SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_COUNT
        FROM REST_REVIEW
        GROUP BY
            MEMBER_ID
        ORDER BY
            REVIEW_COUNT DESC
        LIMIT 1
    ) AS MOST_REVIEWS ON P.MEMBER_ID = MOST_REVIEWS.MEMBER_ID
ORDER BY REVIEW_DATE, R.REVIEW_TEXT