-- 코드를 작성해주세요
SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (SELECT MAX(SIZE_OF_COLONY)
    FROM ECOLI_DATA
    WHERE YEAR(E.DIFFERENTIATION_DATE) = YEAR(ECOLI_DATA.DIFFERENTIATION_DATE))
    - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
ORDER BY YEAR(E.DIFFERENTIATION_DATE), YEAR_DEV;