-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단' AND MONTH(H.START_DATE) = 10
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;